Adding CMakeLists.txt and README for the OpenACC Validation and Verif…
llvm-doe-org/llvm-test-suite pull request #1
Opened 2022-09-23 15:38 UTC by Vaidh10

Adding CMakeLists.txt and README for the OpenACC Validation and Verification Suite so it can be built as part of the LLVM test-suite

2022-09-30 20:40 UTC, jdenny-ornl requested changes
Thanks for developing this!  Please address my inline review comments, and then I think we can merge this.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/README
> +This directory contains a CMakeLists.txt for the OpenACC Validation and Verification Suite so it can be built as part
Where possible, please make all text and code fit within 80 columns.  This is required by the LLVM coding standards.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/README
> +cmake ../llvm-test-suite -DCMAKE_BUILD_TYPE=Release -DTEST_SUITE_OPENACCVV_ROOT=${HOME}/OpenACCV-V -DTEST_SUITE_LIT=${CLACC_BUILD_DIR}/../build/bin/llvm-lit -DCMAKE_C_COMPILER=${CLACC_BUILD_DIR}/bin/
Please format this line in the same manner as the SOLLVE README does: prefix with `$` and use `\` to fit within 80 columns.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/README
> +cmake ../llvm-test-suite -DCMAKE_BUILD_TYPE=Release -DTEST_SUITE_OPENACCVV_ROOT=${HOME}/OpenACCV-V -DTEST_SUITE_LIT=${CLACC_BUILD_DIR}/../build/bin/llvm-lit -DCMAKE_C_COMPILER=${CLACC_BUILD_DIR}/bin/
This command just configures.  Please add the command needed to run the test suite.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/CMakeLists.txt
> +  set(_includedir "${CLACC_BUILD_DIR}/runtimes/runtimes-bins/openmp")
Where is `_includedir` used?  If it's not used, then I don't think `CLACC_BUILD_DIR` has to be defined as a cmake variable, as shown in `README`.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/README
> +cmake ../llvm-test-suite -DCMAKE_BUILD_TYPE=Release -DTEST_SUITE_OPENACCVV_ROOT=${HOME}/OpenACCV-V -DTEST_SUITE_LIT=${CLACC_BUILD_DIR}/../build/bin/llvm-lit -DCMAKE_C_COMPILER=${CLACC_BUILD_DIR}/bin/
The name `CLACC_BUILD_DIR` suggests the specified `clang` executable should be the one from the Clacc build directory.  However, the use of `${CLACC_BUILD_DIR}/../build` suggests `CLACC_BUILD_DIR` is actually the Clacc install directory.  I think the latter is the intention.  If so, please rename to `CLACC_INSTALL_DIR`.

2022-09-30 20:40 UTC, jdenny-ornl commented on External/openacc_vv/CMakeLists.txt
> +    string(REPLACE "." "" _directory "${_directory}")
Where is `_directory` used?

2022-10-04 22:06 UTC, jdenny-ornl requested changes
Thanks for applying those changes.  There's one more issue I just noticed.

2022-10-04 22:06 UTC, jdenny-ornl commented on External/openacc_vv/CMakeLists.txt
> +    set(_name "${_basename}-${_ext}")
This code transforms test file names like `acc_delete.c` into `acc_delete-c`.  I understand sollve did the same thing, but I don't know why.  Do you?

I find it cumbersome to have to manually perform this transformation whenever I copy and paste a test file name as written in the actual OpenACC V&V suite into, say, `LIT_FILTER`.

Unless it's really needed, I suggest we drop this code and just use `${_file}` where `${_name}` is currently used.

2022-10-07 22:03 UTC, Vaidh10 commented on External/openacc_vv/CMakeLists.txt
> +    set(_name "${_basename}-${_ext}")
I am not entirely sure about the reason for usage of file name transformation in the sollve project. I Updated the code accordingly. Thanks!

2022-10-10 15:36 UTC, merged

2022-10-10 15:36 UTC, jdenny-ornl commented
@Vaidh10 Thanks!